In [20]:
import numpy as np

from typing import Callable

In [3]:
print("Python list operations:")
a = [1,2,3]
b = [4,5,6]
print("a+b:", a+b)

try:
    print(a*b)
except TypeError:
    # does not make sense
    print("a*b has no meaning for Python lists")

print()
print("numpy array operations:")
a = np.array([1,2,3])
b = np.array([4,5,6])
print("a+b:", a+b)
print("a*b:", a*b)

Python list operations:
a+b: [1, 2, 3, 4, 5, 6]
a*b has no meaning for Python lists

numpy array operations:
a+b: [5 7 9]
a*b: [ 4 10 18]


In [9]:
a = np.array([[1, 2], [3, 4]])
print('a:')
print(a)
print('a.sum(axis=0):', a.sum(axis=0))
print('a.sum(axis=1):', a.sum(axis=1))

a:
[[1 2]
 [3 4]]
a.sum(axis=0): [4 6]
a.sum(axis=1): [3 7]


In [11]:
a = np.array([[1,2,3],[4,5,6]])
b = np.array([10,20,30])
print("a+b:\n", a+b)

a+b:
 [[11 22 33]
 [14 25 36]]


## Derivatives

In [22]:
def deriv(func: Callable[[np.ndarray], np.ndarray],
          input_: np.ndarray,
          delta: float = 0.001) -> np.ndarray:
    return (func(input_ + delta) - func(input_ - delta)) / (2 * delta)
'''
Evaluates the derivative of a function "func" at every element in the "input_" array.
'''

'\nEvaluates the derivative of a function "func" at every element in the "input_" array.\n'